CREATE DATABASE Carometro_Nota10;
GO

USE Carometro_Nota10;
GO

CREATE TABLE TIPO_USUARIO(
	idTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
	nomeTipoUser VARCHAR(50)

);

CREATE TABLE USUARIO(
	idUsuario SMALLINT PRIMARY KEY IDENTITY (1,1),
	idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPO_USUARIO(idTipoUsuario),
	email VARCHAR(50) UNIQUE,
	senha VARCHAR(20),
	nomeUsuario VARCHAR(50),
	fotoUsuario VARCHAR(200)

);

CREATE TABLE PROFESSOR(
	idProfessor SMALLINT PRIMARY KEY IDENTITY (1,1),
	idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario)

);

CREATE TABLE ADMINISTRADOR(
	idAdministrador SMALLINT PRIMARY KEY IDENTITY (1,1),
	idUsuario SMALLINT FOREIGN KEY REFERENCES USUARIO(idUsuario)

);

CREATE TABLE SALA(
	idSala SMALLINT PRIMARY KEY IDENTITY (1,1),
	idAdministrador SMALLINT FOREIGN KEY REFERENCES ADMINISTRADOR(idAdministrador),
	idProfessor SMALLINT FOREIGN KEY REFERENCES PROFESSOR(idProfessor),
	nomeSala VARCHAR(50),
	numeroSala VARCHAR(20)

);

CREATE TABLE ALUNO(
	idAluno SMALLINT PRIMARY KEY IDENTITY (1,1),
	idSala SMALLINT FOREIGN KEY REFERENCES SALA(idSala),
	nomeAluno VARCHAR(50),
	rm VARCHAR(20),
	telefone VARCHAR(11),
	fotoDoPerfil VARCHAR(200),
	situacao VARCHAR(20)

);